name: ekyc

description: A new Flutter project.

version: 1.0.0+1

environment: 
  sdk: ">=2.19.3 <3.0.0"

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  cached_network_image: ^3.2.1
  intl: ^0.18.0
  go_router: ^13.0.0
  pinput: ^3.0.1
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_signaturepad: ^24.1.43
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.5
  flutter_scrolling_fab_animated: ^0.1.4
  camera: ^0.10.5+8
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  device_info_plus: ^9.1.1
  platform_device_id: ^1.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.4
  encrypt: ^5.0.3
  internet_connection_checker_plus: ^2.2.0
  get_storage: ^2.1.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  flutter_lints: ^3.0.1
    
flutter: 
  uses-material-design: true
  
  assets: 
    - assets/
    - assets/images/

  fonts: 
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-ExtraLight.ttf
          weight: 200

    - family: Isidora Sans
      fonts: 
        # - asset: assets/fonts/Isidora-Sans/isidorasans-black.otf
        #   weight: 900
        - asset: assets/fonts/Isidora-Sans/Isidora-Bold.otf
          weight: 700
        # - asset: assets/fonts/Isidora-Sans/isidorasans-semibold.otf
        #   weight: 600
        - asset: assets/fonts/Isidora-Sans/Isidora-Medium.otf
          weight: 500
        # - asset: assets/fonts/Isidora-Sans/isidorasans-regular.otf
        #   weight: 400
        # - asset: assets/fonts/Isidora-Sans/isidorasans-light.otf
        #   weight: 300
        # - asset: assets/fonts/Isidora-Sans/isidorasans-thin.otf
        #   weight: 200
  
      
      
  