name: ekyc
 
description: A new Flutter project.
 
# Production
# version: 1.0.1+2
 
# Development
version: 2.5.4+45

environment: 
  sdk: '>=3.4.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  go_router: ^13.2.0
  pinput: ^4.0.0
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_signaturepad: ^25.1.35
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.0
  dotted_border: ^2.1.0
  flutter_scrolling_fab_animated: ^0.1.4
  image_picker: ^1.0.7
  # camera: ^0.10.5+9
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  get_it: ^7.6.7
  injectable: ^2.4.0
  platform_device_id: ^1.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.4
  encrypt: ^5.0.3
  internet_connection_checker_plus: ^2.2.0
  get_storage: ^2.1.1
  safe_device: ^1.1.6
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  local_auth: ^2.1.8
  url_launcher: ^6.2.4
  shimmer: ^3.0.0
  # google_mlkit_text_recognition: ^0.11.0
  # google_mlkit_document_scanner: ^0.2.0
  # docscan: ^1.1.6
  # cunning_document_scanner: ^1.2.3
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  firebase_analytics: ^10.10.2
  path_provider: ^2.1.3
  open_file: ^3.3.2
  # crop_your_image: ^1.1.0
  image_cropper: ^8.0.1
  # image_cropping: ^0.0.14
  # file_picker: ^8.0.6
  pdf: ^3.11.1
  multiple_image_camera: ^0.0.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^3.0.0-dev.11
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.0
  flutter_lints: ^3.0.1
  icons_launcher: ^2.1.7
 
dependency_overrides:
  analyzer:
  meta: ^1.12.0

icons_launcher:
  image_path: 'assets/images/launcher_icon/launcher_icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    
flutter: 
  uses-material-design: true
 
  assets:
    - assets/
    - assets/images/
    - assets/images/launcher_icon/
 
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-ExtraLight.ttf
          weight: 200
 
    - family: Isidora Sans
      fonts:
        # - asset: assets/fonts/Isidora-Sans/isidorasans-black.otf
        #   weight: 900
        - asset: assets/fonts/Isidora-Sans/Isidora-Bold.otf
          weight: 700
        # - asset: assets/fonts/Isidora-Sans/isidorasans-semibold.otf
        #   weight: 600
        - asset: assets/fonts/Isidora-Sans/Isidora-Medium.otf
          weight: 500
        # - asset: assets/fonts/Isidora-Sans/isidorasans-regular.otf
        #   weight: 400
        # - asset: assets/fonts/Isidora-Sans/isidorasans-light.otf
        #   weight: 300
        # - asset: assets/fonts/Isidora-Sans/isidorasans-thin.otf
        #   weight: 200