import 'dart:convert';

import 'package:ekyc/core/app_export.dart';
import 'package:ekyc/features/profile/data/models/get_agent_details/response/get_agent_details_response_model.dart';
import 'package:ekyc/features/profile/presentation/providers/get_agent_details_provider.dart';
import 'package:ekyc/features/signature/presentation/mixins/signature_mixin.dart';
import 'package:ekyc/features/signature/presentation/providers/signature_base64_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class DemoFile extends ConsumerStatefulWidget {
  const DemoFile({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _DemoFileState();
}

class _DemoFileState extends ConsumerState<DemoFile> with SignatureMixin {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    getSignature(context: context, ref: ref);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          _agentDetailsWidget(),
        ],
      ),
    );
  }

  Widget _agentDetailsWidget() {
    final GetAgentDetailsResponseModel? getAgentDetailsResponse = ref.watch(agentDetailsResponseProvider);
    final GetAgentDetailsResponseBody? agentDetails = getAgentDetailsResponse?.body?.responseBody;

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        border: Border.all(
          color: black,
          width: 1,
        ),
        borderRadius: BorderRadius.circular(16),
        color: white,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            "Certified true copy of the original",
            style: TextStyle(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 16),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    _agentDetailsItem(
                        title: "Full Name", value: "${agentDetails?.agentName ?? ""} ${agentDetails?.lastName ?? ""}"),
                    const SizedBox(height: 32),
                    _agentDetailsItem(title: "Job Title", value: agentDetails?.designation ?? ""),
                  ],
                ),
              ),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    _agentDetailsItem(title: "Address", value: agentDetails?.address ?? ""),
                    const SizedBox(height: 32),
                    _agentDetailsItem(title: "Date & Time", value: agentDetails?.designation ?? ""),
                  ],
                ),
              ),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    _agentDetailsItem(title: "Email", value: agentDetails?.emailId ?? ""),
                    const SizedBox(height: 32),
                    _agentSignatureWidget(ref),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          const Text(
            "[Automatically generated by MUA Mauritius Union Assurance Cy Ltd/Head office]",
            style: TextStyle(
              color: textGrayColor2,
              fontWeight: FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  Widget _agentSignatureWidget(WidgetRef ref) {
    debugPrint("inside agent signature widget");

    String? signatureBase64 = ref.watch(signatureBase64Provider);
    debugPrint("signatureBase64 inside agent signature widget: $signatureBase64");

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          Strings.signature,
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.bold,
          ),
        ),
        if (signatureBase64 == null) ...[
          SizedBox(
            height: 100.h,
          )
        ] else ...[
          Image.memory(
            base64Decode(signatureBase64),
            height: 100,
          ),
        ],
      ],
    );
  }

  Widget _agentDetailsItem({required String title, required String value}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.bold,
          ),
        ),
        Text(
          value,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
          ),
        ),
      ],
    );
  }
}
